definitions:
  config:
    /hippo:namespaces/dynamiccomponentsdemo/Default:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 5f7d6e26-f3dd-43b2-bef6-5f880777f3d5
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 3180315f-dc30-4f86-bc64-fd67b3b74941
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:node: true
          hipposysedit:supertype: ['hippogallery:imageset', 'hippogallery:relaxed']
          hipposysedit:uri: http://www.dynamiccomponentsdemo.com/dynamiccomponentsdemo/nt/1.0
          /filename:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:filename
            hipposysedit:type: String
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:description
            hipposysedit:type: String
          /thumbnail:
            jcr:primaryType: hipposysedit:field
            hipposysedit:autocreated: true
            hipposysedit:mandatory: true
            hipposysedit:path: hippogallery:thumbnail
            hipposysedit:primary: true
            hipposysedit:type: hippogallery:image
          /original:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:original
            hipposysedit:type: hippogallery:image
          /cta:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: dynamiccomponentsdemo:cta
            hipposysedit:type: hippogallery:image
          /banner:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: dynamiccomponentsdemo:banner
            hipposysedit:type: hippogallery:image
          /column:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: dynamiccomponentsdemo:column
            hipposysedit:type: hippogallery:image
          /columnTablet:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: dynamiccomponentsdemo:columnTablet
            hipposysedit:type: hippogallery:image
          /columnMobile:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: dynamiccomponentsdemo:columnMobile
            hipposysedit:type: hippogallery:image
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: dynamiccomponentsdemo:Default
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 8f3436e3-1034-4e14-8bca-cb825e91512b
          /hippogallery:thumbnail:
            jcr:primaryType: hippogallery:image
            jcr:data:
              type: binary
              resource: /namespaces/dynamiccomponentsdemo/Default/prototypes/prototype/thumbnail/thumbnail.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
          /hippogallery:original:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 0
            hippogallery:width: 0
            jcr:data:
              type: binary
              resource: /namespaces/dynamiccomponentsdemo/Default/prototypes/prototype/original/original.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [model.compareTo, wicket.model, engine]
          frontend:services: [wicket.id]
          mode: edit
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /filename:
            jcr:primaryType: frontend:plugin
            caption: file name
            field: filename
            plugin.class: org.hippoecm.frontend.plugins.gallery.editor.FileNameDisplayPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /thumbnail:
            jcr:primaryType: frontend:plugin
            caption: thumbnail
            field: thumbnail
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /original:
            jcr:primaryType: frontend:plugin
            caption: original
            field: original
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /cta:
            jcr:primaryType: frontend:plugin
            caption: cta
            field: cta
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /banner:
            jcr:primaryType: frontend:plugin
            caption: banner
            field: banner
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /column:
            jcr:primaryType: frontend:plugin
            caption: column
            field: column
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /columnTablet:
            jcr:primaryType: frontend:plugin
            caption: columnTablet
            field: columnTablet
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /columnMobile:
            jcr:primaryType: frontend:plugin
            caption: columnMobile
            field: columnMobile
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
